#!/bin/sh

cd `dirname $0`
cd Olive

#read -p "请拖入待处理的项目文件夹:" projectPath
#
#if  [ ! -n "$projectPath" ] ;then
#echo "您没有输入任何内容🤪"
#exit 0
#fi

#这里把所有deb的信息写入到Packages里面去,自动生成1个Packages
dpkg-scanpackages debs > Packages
bzip2 -fks Packages

#find ../ -name ".DS_Store" -depth -exec rm {} \;
#
#for file in `ls ../projects`
#    do
#      if [[ -d "../projects/$file" ]]; then
#        mkdir -p "./debs/$file"
#        dpkg-deb -bZgzip "../projects/$file" "./debs/$file"
#            fi
#    done
#dpkg-scanpackages -m ./debs > ./Packages
#bzip2 -fks ./Packages

#创建Release
#apt-ftparchive release ./ > Release

#Origin: SmartSnake软件源™
#Label: JiaYi
#Suite: stable
#Version: 0.0.1
#Codename: SmartSnake
#Architectures: iphoneos-arm
#Components: main
#Description: SmartSnake软件源

exit 0
